### ISSUE TITLE
Fetch distros from API instead

### ISSUE THREAD

**Issue by capotej** [mlafeldt/pkgcloud#1]
Nice library!

One small note: https://github.com/mlafeldt/pkgcloud/blob/master/distros.go#L17

You should fetch the list of distributions from our API instead: https://packagecloud.io/docs/api#resource_distributions_method_index, that way whenever we add a new one you don't have to update your library.

Cheers

**Comment by mlafeldt** [comment]
Thanks, @capotej!

I actually used that API endpoint to generate the distro list when starting the project (0754e9a10ad5ee52a99a4d8fb4cc4cc39a9bdb5a). I decided against using the API at runtime because it's not that easy to parse and kind of slow. More importantly, I wanted to get uploading work first. :)

That being said, fetching the supported distros from your API would still be the right thing to do and I might add it later on.

**Comment by mlafeldt** [comment]
@capotej I'm actually wondering why you use distro IDs on the client side in the first place? Any reason why you're not translating distro names to IDs in the backend? This seems to make the interface a lot more complicated, IMHO. Maybe I'm missing something. Please enlighten me.

**Comment by capotej** [comment]
No reason in particular other than it being the easiest choice at the time, our next API version most likely will not be using id's.

**Comment by mlafeldt** [comment]
I see. At the moment, it also seems impossible to list all packages of a repository. Among other things, this makes it hard to delete packages by name.

(Background: I want to clean up old versions of a package when pushing a new version. This cleanup is required due to the limit of 25 packages - even with the $20 plan.)

**Comment by mlafeldt** [comment]
Sticking with the hardcoded list for the reasons outlined above.

**Comment by capotej** [comment]
That sounds fine, we're working on adding package listing to the API soon.

Also wanted to give you a heads up that we added some distributions recently so you might want to regenerate the list. :)
